-- ═══════════════════════════════════════════════════════════
--  PathPilot v2 — Seed Data
-- ═══════════════════════════════════════════════════════════

-- ─────────────────────────────────────────
-- CAREER PATHS (20+ diverse paths across all fields)
-- ─────────────────────────────────────────
INSERT INTO career_paths (title, field, description, avg_salary_inr, avg_salary_usd, growth_rate, difficulty, time_to_entry, required_skills, nice_to_have_skills, recommended_courses, top_companies, job_roles, icon_emoji, quiz_tags) VALUES

('Full Stack Developer', 'Technology',
 'Build complete web applications — from beautiful UIs to robust APIs and databases. High demand across every industry.',
 '₹6L – ₹25L/yr', '$85K – $130K/yr', '25% (Much faster)', 'moderate', '6–12 months',
 ARRAY['HTML/CSS','JavaScript','React/Vue','Node.js','SQL','Git','REST APIs'],
 ARRAY['TypeScript','Docker','AWS','Redis'],
 ARRAY['The Odin Project','freeCodeCamp','Full Stack Open','CS50 Web'],
 ARRAY['Google','Infosys','Startups','Freelance'],
 ARRAY['Frontend Developer','Backend Developer','Full Stack Engineer','Software Engineer','Web Developer','Application Developer'],
 '💻', ARRAY['tech','coding','problem-solving','building']),

('Data Scientist', 'Technology',
 'Extract insights from complex datasets using statistics, machine learning, and storytelling to drive smarter decisions.',
 '₹8L – ₹30L/yr', '$95K – $145K/yr', '35% (Much faster)', 'hard', '8–18 months',
 ARRAY['Python','Statistics','Machine Learning','SQL','Data Visualization','Pandas','NumPy'],
 ARRAY['Deep Learning','Spark','Cloud ML','R'],
 ARRAY['Fast.ai','Kaggle Learn','Applied ML (Coursera)','StatQuest YouTube'],
 ARRAY['Amazon','Microsoft','Flipkart','Research Labs','Startups'],
 ARRAY['Data Scientist','Machine Learning Engineer','Data Analyst','AI Engineer','Business Intelligence Analyst','Research Scientist'],
 '📊', ARRAY['data','analysis','math','research','patterns']),

('UX/UI Designer', 'Design',
 'Design digital experiences that are beautiful, intuitive, and meaningful. The bridge between users and technology.',
 '₹5L – ₹20L/yr', '$70K – $115K/yr', '13% (Faster)', 'moderate', '4–10 months',
 ARRAY['Figma','User Research','Wireframing','Prototyping','Typography','Color Theory'],
 ARRAY['Motion Design','Framer','Accessibility','Design Systems'],
 ARRAY['Google UX Certificate','Interaction Design Foundation','Refactoring UI'],
 ARRAY['Adobe','Swiggy','Zomato','Design Agencies','Startups'],
 ARRAY['UX Designer','UI Designer','Product Designer','Design Lead'],
 '🎨', ARRAY['design','creativity','empathy','visual','art']),

('Product Manager', 'Business',
 'Own the product vision. Work at the intersection of tech, business, and user needs to ship features that matter.',
 '₹10L – ₹35L/yr', '$90K – $140K/yr', '10% (Average)', 'hard', '1–3 years (usually after other roles)',
 ARRAY['Product Strategy','User Research','Agile/Scrum','Analytics','Communication','SQL'],
 ARRAY['A/B Testing','Growth Hacking','Finance Basics'],
 ARRAY['Reforge','Product School','Lenny''s Newsletter','PM Exercises'],
 ARRAY['Razorpay','CRED','Google','Microsoft','Startups'],
 ARRAY['Product Manager','Technical Project Manager','Associate Product Manager','Senior PM','Head of Product'],
 '🗺️', ARRAY['leadership','strategy','business','communication','planning']),

('Cybersecurity Analyst', 'Technology',
 'Defend organizations from digital threats. Monitor, detect, respond, and prevent attacks in a high-stakes field.',
 '₹5L – ₹22L/yr', '$80K – $125K/yr', '32% (Much faster)', 'hard', '6–15 months',
 ARRAY['Networking','Linux','Python','SIEM Tools','Ethical Hacking','Cryptography'],
 ARRAY['Cloud Security','Forensics','Reverse Engineering'],
 ARRAY['CompTIA Security+','TryHackMe','Cybrary','EC-Council CEH'],
 ARRAY['TCS','HCL','CERT-In','Banks','Government'],
 ARRAY['Cybersecurity Analyst','SOC Analyst','Penetration Tester','Security Engineer','Information Security Analyst','Security Consultant'],
 '🛡️', ARRAY['security','tech','problem-solving','detective-thinking']),

('Digital Marketing Specialist', 'Business',
 'Grow brands online using SEO, social media, paid advertising, email campaigns, and data-driven content strategies.',
 '₹3L – ₹15L/yr', '$55K – $90K/yr', '10% (Average)', 'easy', '2–6 months',
 ARRAY['SEO/SEM','Google Analytics','Meta Ads','Content Strategy','Email Marketing','Copywriting'],
 ARRAY['Video Marketing','Marketing Automation','CRO'],
 ARRAY['Google Digital Garage','HubSpot Academy','CXL Institute','Moz Blog'],
 ARRAY['Agencies','E-commerce','Media Companies','Startups'],
 ARRAY['SEO Specialist','Performance Marketer','Content Strategist','Growth Hacker'],
 '📣', ARRAY['marketing','communication','creativity','social-media','writing']),

('Mobile App Developer', 'Technology',
 'Build apps used by millions on iOS and Android. From indie apps to enterprise solutions.',
 '₹6L – ₹22L/yr', '$80K – $125K/yr', '22% (Much faster)', 'moderate', '6–12 months',
 ARRAY['React Native or Flutter','JavaScript or Dart','REST APIs','Git','App Store Deployment'],
 ARRAY['Native iOS (Swift)','Native Android (Kotlin)','Firebase','Redux'],
 ARRAY['Flutter.dev docs','React Native docs','Angela Yu iOS Course','Academind'],
 ARRAY['Startups','Gaming Companies','Health-tech','Freelance'],
 ARRAY['Mobile App Developer','Application Developer','iOS Developer','Android Developer','Flutter Developer','React Native Developer'],
 '📱', ARRAY['tech','coding','building','mobile','apps']),

('Cloud & DevOps Engineer', 'Technology',
 'Build and maintain the infrastructure that powers the internet. Automate, scale, and ensure reliability.',
 '₹8L – ₹30L/yr', '$95K – $140K/yr', '28% (Much faster)', 'hard', '8–18 months',
 ARRAY['Linux','Docker','Kubernetes','AWS/GCP/Azure','CI/CD','Python/Bash','Terraform'],
 ARRAY['Prometheus','Grafana','Service Mesh'],
 ARRAY['AWS Solutions Architect','Linux Foundation','KodeKloud','A Cloud Guru'],
 ARRAY['Amazon','Microsoft','Deloitte','Infra Startups'],
 ARRAY['DevOps Engineer','Cloud Engineer','Cloud Architect','Site Reliability Engineer','Platform Engineer','Infrastructure Engineer'],
 '☁️', ARRAY['tech','infrastructure','automation','problem-solving']),

('Frontend Developer', 'Technology',
 'Build fast, accessible, and responsive user interfaces for modern web applications.',
 '₹5L – ₹20L/yr', '$75K – $120K/yr', '23% (Much faster)', 'moderate', '4–10 months',
 ARRAY['HTML/CSS','JavaScript','React','Responsive Design','Git','APIs'],
 ARRAY['TypeScript','Next.js','Accessibility','Testing Library'],
 ARRAY['Frontend Mentor','Scrimba Frontend Path','freeCodeCamp','React Docs'],
 ARRAY['Startups','Product Companies','Agencies','Freelance'],
 ARRAY['Frontend Developer','UI Developer','React Developer','JavaScript Developer','Web Developer'],
 '🖥️', ARRAY['tech','coding','building','ui','frontend']),

('Backend Developer', 'Technology',
 'Design APIs, business logic, and databases that power web and mobile products behind the scenes.',
 '₹6L – ₹24L/yr', '$80K – $130K/yr', '24% (Much faster)', 'moderate', '6–12 months',
 ARRAY['Python or Node.js','REST APIs','SQL','Git','Authentication','System Design Basics'],
 ARRAY['Docker','Caching','Message Queues','GraphQL'],
 ARRAY['Node.js Docs','FastAPI Docs','CS50 API','Backend Engineering Blogs'],
 ARRAY['SaaS Companies','Fintech','Startups','Enterprise Teams'],
 ARRAY['Backend Developer','API Developer','Python Developer','Node.js Developer','Software Engineer'],
 '🧩', ARRAY['tech','coding','backend','apis','problem-solving']),

('AI / ML Engineer', 'Technology',
 'Train, deploy, and improve intelligent systems using machine learning, deep learning, and applied AI.',
 '₹8L – ₹32L/yr', '$100K – $155K/yr', '35% (Much faster)', 'hard', '8–18 months',
 ARRAY['Python','Machine Learning','Deep Learning','Linear Algebra','SQL','Model Deployment'],
 ARRAY['MLOps','LLMs','PyTorch','Cloud ML'],
 ARRAY['Fast.ai','DeepLearning.AI','Kaggle Learn','Hands-On ML'],
 ARRAY['AI Startups','Research Labs','Big Tech','Product Companies'],
 ARRAY['ML Engineer','AI Engineer','Applied Scientist','MLOps Engineer','Research Engineer'],
 '🤖', ARRAY['tech','ai','machine-learning','data','research']),

('QA / Automation Engineer', 'Technology',
 'Ensure software quality through manual testing, automation, bug tracking, and release confidence.',
 '₹4L – ₹16L/yr', '$65K – $105K/yr', '17% (Faster)', 'moderate', '4–9 months',
 ARRAY['Manual Testing','Test Cases','Bug Reporting','Automation Basics','APIs','SQL'],
 ARRAY['Selenium','Playwright','CI/CD','Performance Testing'],
 ARRAY['ISTQB','Playwright Docs','Selenium Docs','Test Automation University'],
 ARRAY['Product Companies','QA Firms','Startups','Enterprise Teams'],
 ARRAY['QA Engineer','Automation Engineer','Software Test Engineer','SDET','Quality Analyst'],
 '✅', ARRAY['tech','testing','quality','problem-solving','automation']),

('Network Engineer', 'Technology',
 'Plan, secure, and maintain computer networks that keep organizations connected and online.',
 '₹4.5L – ₹18L/yr', '$70K – $115K/yr', '11% (Average)', 'moderate', '6–12 months',
 ARRAY['Networking','TCP/IP','Routing & Switching','Linux','Network Security','Troubleshooting'],
 ARRAY['Cloud Networking','Firewalls','Wireless Networks','Python Automation'],
 ARRAY['Cisco CCNA','NetworkChuck','CompTIA Network+','Juniper Training'],
 ARRAY['Telecom Companies','Data Centers','MSPs','Enterprise IT'],
 ARRAY['Network Engineer','Network Administrator','NOC Engineer','Infrastructure Engineer','Systems Engineer'],
 '🌐', ARRAY['tech','networking','infrastructure','security','problem-solving']),

('Database Administrator', 'Technology',
 'Manage databases, optimize performance, protect backups, and keep critical data systems healthy.',
 '₹5L – ₹20L/yr', '$75K – $120K/yr', '12% (Average)', 'moderate', '6–12 months',
 ARRAY['SQL','Database Design','Backups','Performance Tuning','Linux','Monitoring'],
 ARRAY['PostgreSQL','MySQL','Replication','Cloud Databases'],
 ARRAY['PostgreSQL Docs','Mode SQL','Database Design Courses','Oracle Learning'],
 ARRAY['Banks','SaaS Companies','Consulting Firms','Enterprise IT'],
 ARRAY['Database Administrator','Database Engineer','SQL Developer','Data Platform Engineer','Performance Tuning Specialist'],
 '🗄️', ARRAY['tech','data','sql','infrastructure','analysis']),

('IT Support / Systems Administrator', 'Technology',
 'Support users, maintain systems, manage devices, and keep day-to-day IT operations running smoothly.',
 '₹3L – ₹12L/yr', '$45K – $80K/yr', '9% (Average)', 'easy', '3–6 months',
 ARRAY['Computer Hardware','Windows/Linux','Troubleshooting','Networking Basics','Documentation','Communication'],
 ARRAY['Active Directory','Ticketing Tools','PowerShell','Security Basics'],
 ARRAY['Google IT Support','CompTIA A+','Microsoft Learn','Help Desk Labs'],
 ARRAY['IT Services','Schools','Hospitals','Corporate IT Departments'],
 ARRAY['IT Support Specialist','System Administrator','Desktop Support Engineer','Technical Support Engineer','Helpdesk Analyst'],
 '🛠️', ARRAY['tech','support','systems','troubleshooting','communication']),

('Game Developer', 'Technology',
 'Create gameplay systems, mechanics, and interactive worlds for PC, console, and mobile games.',
 '₹5L – ₹22L/yr', '$70K – $125K/yr', '16% (Faster)', 'hard', '8–18 months',
 ARRAY['C# or C++','Unity or Unreal','Game Physics','Problem-Solving','Math','Git'],
 ARRAY['Shaders','3D Math','Multiplayer','Game Design'],
 ARRAY['Unity Learn','Unreal Engine Docs','Brackeys','GameDev.tv'],
 ARRAY['Gaming Studios','Indie Teams','AR/VR Startups','Freelance'],
 ARRAY['Game Developer','Gameplay Programmer','Unity Developer','Unreal Developer','Game Programmer'],
 '🎮', ARRAY['tech','coding','games','creativity','building']),

('Content Creator / YouTuber', 'Media',
 'Build an audience by creating valuable video, written, or audio content. Monetize through ads, sponsorships, and products.',
 '₹1L – ₹50L+/yr', '$10K – $500K+/yr', '15% (Faster)', 'easy', '1–3 years to monetize',
 ARRAY['Video Editing','Storytelling','SEO','Thumbnail Design','Scriptwriting','Analytics'],
 ARRAY['Premiere Pro','After Effects','Podcast Production'],
 ARRAY['YouTube Creator Academy','Canva Design School','Think Media YouTube'],
 ARRAY['YouTube','Instagram','Podcasting Platforms','Brand Deals'],
 ARRAY['YouTuber','Podcaster','Blogger','Course Creator','Brand Ambassador'],
 '🎬', ARRAY['creativity','communication','storytelling','media','art']),

('Financial Analyst', 'Finance',
 'Analyze financial data, forecast trends, and provide investment recommendations to drive business strategy.',
 '₹5L – ₹20L/yr', '$65K – $110K/yr', '9% (Average)', 'moderate', '6–12 months',
 ARRAY['Excel/Google Sheets','Financial Modeling','Accounting Basics','Statistics','Python'],
 ARRAY['Bloomberg','Power BI','SQL','CFA Certification'],
 ARRAY['CFI Financial Modeling','Coursera Finance Specialization','CFA Program'],
 ARRAY['Banks','NBFC','Big 4 Firms','Investment Firms','Startups'],
 ARRAY['Financial Analyst','Investment Analyst','Equity Researcher','CFO (senior)'],
 '💹', ARRAY['finance','numbers','analysis','business','math']),

('Doctor / Medical Professional', 'Healthcare',
 'Provide healthcare, diagnose illnesses, and save lives. High respect, strong job security, and global opportunities.',
 '₹10L – ₹50L+/yr', '$130K – $300K+/yr', '16% (Faster)', 'very hard', '5.5–7 years (MBBS + specialization)',
 ARRAY['NEET Exam','Biology','Chemistry','Medicine','Patient Care','Clinical Skills'],
 ARRAY['Surgery','Research','Medical Technology','Hospital Management'],
 ARRAY['NEET Coaching','Medical Colleges','WHO Resources','CME Programs'],
 ARRAY['Hospitals','Clinics','Research Centers','NGOs','Government Health'],
 ARRAY['Doctor','Surgeon','Specialist','Hospital Administrator','Medical Researcher'],
 '⚕️', ARRAY['healthcare','science','helping','research','problem-solving']),

('Nurse / Healthcare Technician', 'Healthcare',
 'Provide compassionate patient care, support doctors, and make a direct impact on people''s health and recovery.',
 '₹2.5L – ₹8L/yr', '$35K – $60K/yr', '18% (Faster)', 'moderate', '2–3 years',
 ARRAY['Medical Knowledge','Patient Care','Empathy','Communication','Lab Skills','Anatomy'],
 ARRAY['ICU Nursing','Critical Care','Medical Technology'],
 ARRAY['Nursing Colleges','Red Cross Training','WHO Protocols','Online Courses'],
 ARRAY['Hospitals','Clinics','NGOs','Ambulance Services','Home Care'],
 ARRAY['Registered Nurse','Nursing Assistant','ICU Technician','Medical Technologist'],
 '🏥', ARRAY['healthcare','helping','science','empathy','caring']),

('Teacher / Educator', 'Education',
 'Shape young minds, inspire learning, and build the future. Make a meaningful difference in students'' lives.',
 '₹2.5L – ₹10L/yr', '$30K – $75K/yr', '8% (Average)', 'easy', '1–4 years (B.Ed or M.Ed)',
 ARRAY['Subject Expertise','Communication','Patience','Curriculum Design','Classroom Management'],
 ARRAY['Educational Technology','Special Education','Counseling'],
 ARRAY['B.Ed Programs','CTET','Online Courses','Teaching Certifications'],
 ARRAY['Schools','Colleges','Online Platforms','Coaching Centers','Private Institutions'],
 ARRAY['Teacher','Lecturer','Professor','Curriculum Designer','Education Manager'],
 '📚', ARRAY['education','communication','empathy','helping','teaching']),

('Corporate Trainer / L&D Specialist', 'Education',
 'Develop employee skills, design training programs, and drive organizational development and learning.',
 '₹4L – ₹15L/yr', '$50K – $90K/yr', '12% (Faster)', 'moderate', '3–5 years',
 ARRAY['Instructional Design','Communication','Training Tools','Analytics','Psychology'],
 ARRAY['E-learning Development','Gamification','Leadership Coaching'],
 ARRAY['IDOL Certification','Coursera Learning Design','ATD Programs'],
 ARRAY['Fortune 500 Companies','Consulting Firms','EdTech Startups','Coaching Centers'],
 ARRAY['Training Manager','Instructional Designer','Learning Consultant','HR Manager'],
 '🎓', ARRAY['education','communication','leadership','business','empathy']),

('Civil Engineer', 'Engineering',
 'Design and build infrastructure that society depends on — roads, bridges, buildings, and water systems.',
 '₹5L – ₹20L/yr', '$65K – $110K/yr', '7% (Average)', 'hard', '4–6 years',
 ARRAY['CAD Software','Structural Analysis','Mathematics','Physics','Project Management'],
 ARRAY['BIM','Revit','Site Management','Environmental Engineering'],
 ARRAY['Civil Engineering Colleges','AutoCAD Training','PMP Certification'],
 ARRAY['Larsen & Toubro','Tata Projects','GMR','Construction Companies','Government'],
 ARRAY['Civil Engineer','Project Manager','Structural Engineer','Site Supervisor','Contractor'],
 '🏗️', ARRAY['engineering','problem-solving','math','building','infrastructure']),

('Psychologist / Counselor', 'Healthcare & Social',
 'Help people overcome mental health challenges, provide therapy, and improve overall well-being.',
 '₹3L – ₹12L/yr', '$45K – $85K/yr', '14% (Faster)', 'moderate', '2–4 years',
 ARRAY['Psychology','Counseling Skills','Active Listening','Empathy','Assessment Methods'],
 ARRAY['Clinical Psychology','Cognitive Behavioral Therapy','Research Methods'],
 ARRAY['Psychology Degree','Counseling Certification','IACP Programs','Online Therapies'],
 ARRAY['Hospitals','Mental Health Clinics','Schools','Corporate','NGOs','Private Practice'],
 ARRAY['Counselor','Clinical Psychologist','School Psychologist','Therapist','Life Coach'],
 '🧠', ARRAY['psychology','empathy','helping','caring','listening']),

('Lawyer / Legal Professional', 'Law',
 'Defend justice, advise clients on legal matters, and make a significant impact on law and society.',
 '₹4L – ₹30L+/yr', '$60K – $200K+/yr', '10% (Average)', 'hard', '5–7 years',
 ARRAY['Law','Legal Research','Writing','Communication','Critical Thinking','Ethics'],
 ARRAY['Corporate Law','Criminal Law','Intellectual Property','Litigation'],
 ARRAY['Law Colleges','CLAT Coaching','Bar Association Courses','Online Legal Training'],
 ARRAY['Law Firms','Courts','Corporate Legal','Government','NGOs'],
 ARRAY['Lawyer','Attorney','Judge','Legal Advisor','Patent Agent','Diplomat'],
 '⚖️', ARRAY['law','justice','communication','analysis','leadership']),

('Journalist / Media Professional', 'Media & Communications',
 'Tell stories that matter, investigate truth, and inform the public. Be the voice of society.',
 '₹2.5L – ₹12L/yr', '$40K – $80K/yr', '5% (Slower)', 'moderate', '1–3 years',
 ARRAY['Writing','Research','Interview Skills','Photography/Videography','News Judgment','Ethics'],
 ARRAY['Investigative Journalism','Data Journalism','Podcast Production'],
 ARRAY['Journalism Schools','Online Courses','AP Style Guide','Media Bootcamps'],
 ARRAY['News Organizations','Media Houses','Digital Platforms','Independent Media'],
 ARRAY['Reporter','Editor','Podcast Host','Photojournalist','News Anchor','Freelancer'],
 '📰', ARRAY['communication','writing','research','storytelling','justice']),

('Graphic Designer / Visual Artist', 'Design & Arts',
 'Create stunning visual content that communicates ideas, builds brands, and engages audiences.',
 '₹2.5L – ₹10L/yr', '$35K – $75K/yr', '11% (Average)', 'moderate', '3–6 months (courses) / 4 years (degree)',
 ARRAY['Adobe Creative Suite','Design Principles','Typography','Color Theory','UI/UX Basics'],
 ARRAY['Animation','3D Design','Web Design','Branding'],
 ARRAY['Graphic Design Bootcamps','Design Fundamentals','Skillshare','Domestika'],
 ARRAY['Design Agencies','Advertising','Publishing','Startups','Freelance'],
 ARRAY['Graphic Designer','Brand Designer','Art Director','Design Lead','Freelancer'],
 '🎨', ARRAY['design','creativity','visual','art','communication']),

('Architect', 'Design & Engineering',
 'Design beautiful and functional buildings and spaces that improve how people live and work.',
 '₹5L – ₹20L/yr', '$70K – $120K/yr', '6% (Average)', 'hard', '5–7 years',
 ARRAY['Design','CAD','Building Codes','Spatial Planning','Mathematics','Project Management'],
 ARRAY['BIM','Sustainable Design','3D Visualization','Construction Management'],
 ARRAY['Architecture Schools','Revit Training','AIA Certification','CAD Courses'],
 ARRAY['Architecture Firms','Real Estate','Government','Construction','Urban Planning'],
 ARRAY['Architect','Senior Architect','Design Lead','Project Manager','Urban Planner'],
 '🏢', ARRAY['design','creativity','engineering','problem-solving','planning']),

('Chef / Culinary Professional', 'Hospitality & Food',
 'Create amazing dishes, manage kitchens, and provide unforgettable dining experiences.',
 '₹2L – ₹10L/yr', '$30K – $70K/yr', '9% (Average)', 'moderate', '1–3 years',
 ARRAY['Cooking','Food Safety','Menu Planning','Kitchen Management','Creativity','Communication'],
 ARRAY['Pastry Arts','Nutrition','Food Photography','Restaurant Management'],
 ARRAY['Culinary Schools','Chef Training Programs','Online Cooking Courses','Food Blogs'],
 ARRAY['Hotels','Restaurants','Catering','Cruiseships','Food Startups','Personal Chef'],
 ARRAY['Chef','Sous Chef','Head Chef','Pastry Chef','Food Blogger','Restaurateur'],
 '👨‍🍳', ARRAY['creativity','hospitality','food','management','teaching']),

('Environmental Scientist', 'Environment & Science',
 'Protect the planet by researching environmental issues and developing sustainable solutions.',
 '₹3.5L – ₹12L/yr', '$55K – $90K/yr', '11% (Faster)', 'hard', '2–4 years',
 ARRAY['Environmental Science','Research Methods','Data Analysis','Policy Making','GIS Software'],
 ARRAY['Climate Science','Renewable Energy','Conservation Biology','Sustainability'],
 ARRAY['Environmental Science Degree','GIS Training','Coursera Programs','NGO Internships'],
 ARRAY['Government Agencies','NGOs','Research Institutes','Tech Companies','Startups'],
 ARRAY['Environmental Scientist','Researcher','Conservation Officer','Sustainability Manager'],
 '🌱', ARRAY['environment','science','research','helping','sustainability']),

('Entrepreneur / Startup Founder', 'Business & Entrepreneurship',
 'Build your own business, innovate, and create jobs. Turn your ideas into reality and impact society.',
 '₹0 – ₹100L+/yr', '$0 – $1M+/yr', '20% (Much faster)', 'very hard', 'Variable (experience + network dependent)',
 ARRAY['Business Strategy','Finance','Marketing','Leadership','Problem-Solving','Resilience'],
 ARRAY['Product Development','Fundraising','Sales','Networking'],
 ARRAY['Lean Startup','Business Bootcamps','YCombinator Startup School','NASSCOM Startup Programs'],
 ARRAY['Self-Employed','VC-Backed Startups','Accelerators','Angel Networks'],
 ARRAY['Founder','CEO','Chief Product Officer','Investment Partner (later)'],
 '🚀', ARRAY['business','leadership','innovation','risk-taking','strategy']),

('Human Resources Manager', 'Business & HR',
 'Build great teams, develop talent, and create positive workplace culture that drives business success.',
 '₹3.5L – ₹15L/yr', '$50K – $100K/yr', '10% (Average)', 'moderate', '2–4 years',
 ARRAY['HR Fundamentals','Recruitment','Employee Relations','Performance Management','Communication'],
 ARRAY['SHRM Certification','Labor Laws','HRIS Systems','Organizational Development'],
 ARRAY['SHRM Courses','HR Certification Programs','Online HR Training','Corporate Programs'],
 ARRAY['Tech Companies','Fortune 500','Startups','Consulting Firms','HR Services'],
 ARRAY['HR Manager','Recruiter','HR Specialist','HRBusiness Partner','Talent Manager'],
 '👥', ARRAY['hr','leadership','communication','empathy','business']),

('Photographer / Visual Storyteller', 'Arts & Media',
 'Capture moments and stories through photography. Build a portfolio and monetize your artistic vision.',
 '₹1.5L – ₹10L/yr', '$20K – $80K/yr', '8% (Average)', 'moderate', '1–3 years',
 ARRAY['Photography','Editing Software','Lighting','Composition','Business Skills','Marketing'],
 ARRAY['Videography','Drone Photography','Commercial Photography','Social Media'],
 ARRAY['Photography Bootcamps','YouTube Tutorials','Skillshare','Online Courses','Mentorship'],
 ARRAY['Freelance','Media Companies','Wedding Services','Stock Photo Sites','Brands','Instagram'],
 ARRAY['Photographer','Videographer','Photo Editor','Content Creator','Visual Consultant'],
 '📸', ARRAY['creativity','visual','storytelling','art','technical']),

('Electrician / Skilled Tradesperson', 'Trades & Technical',
 'Learn valuable hands-on skills that are always in demand. Build a profitable career as an independent tradesperson.',
 '₹2.5L – ₹8L/yr', '$40K – $70K/yr', '14% (Faster)', 'moderate', '3–4 years apprenticeship',
 ARRAY['Electrical Systems','Safety','Tools','Building Codes','Problem-Solving','Communication'],
 ARRAY['Solar Installation','HVAC','Automation','Advanced Diagnostics'],
 ARRAY['ITI Programs','Trade Apprenticeships','Certification Courses','On-the-job Training'],
 ARRAY['Construction Companies','Maintenance Services','Government','Self-Employed','Factories'],
 ARRAY['Electrician','Licensed Tradesperson','Site Supervisor','Contractor','Business Owner'],
 '⚡', ARRAY['technical','problem-solving','building','hands-on','practical']),

('Agricultural Expert / Farmer', 'Agriculture',
 'Feed the nation by adopting modern farming techniques. Combine tradition with technology for sustainable agriculture.',
 '₹1.5L – ₹6L/yr', '$25K – $50K/yr', '3% (Slower)', 'moderate', '2–4 years',
 ARRAY['Agronomy','Soil Science','Crop Management','Modern Farming','Irrigation','Marketing'],
 ARRAY['Organic Farming','Precision Agriculture','Agricultural Tech','Horticulture'],
 ARRAY['Agricultural Colleges','ICAR Programs','Online Courses','Government Schemes'],
 ARRAY['Government Agricultural Dept','Agribusiness Companies','Cooperatives','Self-Employed','Export'],
 ARRAY['Farmer','Agricultural Scientist','Extension Officer','Agribusiness Manager'],
 '🌾', ARRAY['agriculture','science','nature','sustainability','business']),

('Social Worker / Community Developer', 'Social Services',
 'Make a real difference in people''s lives by addressing social issues, helping communities, and advocating for justice.',
 '₹2L – ₹8L/yr', '$30K – $60K/yr', '8% (Average)', 'moderate', '2–3 years',
 ARRAY['Social Work','Communication','Problem-Solving','Research','Empathy','Community Engagement'],
 ARRAY['Counseling','Program Management','Advocacy','Policy Development'],
 ARRAY['Social Work Degree','Certificate Programs','NGO Training','Online Courses'],
 ARRAY['NGOs','Government Agencies','International Organizations','Community Centers','Charities'],
 ARRAY['Social Worker','Community Coordinator','Program Manager','Child Protection Officer','Advocate'],
 '❤️', ARRAY['social','empathy','helping','justice','community']),

('Manufacturing / Operations Manager', 'Manufacturing & Operations',
 'Optimize production processes, improve efficiency, and lead teams in a manufacturing or operations environment.',
 '₹4L – ₹15L/yr', '$60K – $110K/yr', '5% (Slower)', 'moderate', '3–5 years',
 ARRAY['Operations','Process Improvement','Quality Control','Team Leadership','Data Analysis','Six Sigma'],
 ARRAY['Lean Manufacturing','Supply Chain','ERP Systems','Project Management'],
 ARRAY['MBA Programs','Operations Certification','Six Sigma Training','Online Courses'],
 ARRAY['Manufacturing Plants','Warehouses','Logistics Companies','Government','Startups'],
 ARRAY['Operations Manager','Production Supervisor','Plant Manager','Supply Chain Manager','Quality Manager'],
 '🏭', ARRAY['operations','management','problem-solving','leadership','technical'])

-- ─────────────────────────────────────────
-- CAREER QUIZ QUESTIONS
-- ─────────────────────────────────────────

INSERT INTO quiz_questions (question, options, category, order_num) VALUES

('When you have free time, what do you naturally gravitate towards?',
 '[
   {"text": "Building or coding something — apps, scripts, tools", "tags": ["tech","coding","building"]},
   {"text": "Designing or creating visual content", "tags": ["design","creativity","visual","art"]},
   {"text": "Reading about business, startups, or finance", "tags": ["business","finance","strategy"]},
   {"text": "Writing, making videos, or telling stories", "tags": ["communication","storytelling","media","writing"]}
 ]'::jsonb, 'interests', 1),

('Which of these problems excites you most to solve?',
 '[
   {"text": "Why is this website slow? How do I make it faster?", "tags": ["tech","problem-solving","infrastructure"]},
   {"text": "Why do users drop off here? How do I improve this experience?", "tags": ["design","empathy","product","ux"]},
   {"text": "Why is this company losing money? What can change?", "tags": ["business","analysis","finance","strategy"]},
   {"text": "How do I help people feel better, be healthier, or solve their real problems?", "tags": ["healthcare","empathy","social","helping","psychology"]}
 ]'::jsonb, 'problem-type', 2),

('What kind of work environment energizes you?',
 '[
   {"text": "Deep solo work — headphones in, in the zone", "tags": ["coding","research","data","writing","hands-on"]},
   {"text": "Creative collaboration — brainstorming with a team", "tags": ["design","product","leadership","creativity","teams"]},
   {"text": "Fast-paced, high-stakes situations or leadership roles", "tags": ["security","finance","leadership","strategy","management"]},
   {"text": "Public-facing — talking, presenting, helping, or leading others", "tags": ["marketing","communication","media","storytelling","education","healthcare"]}
 ]'::jsonb, 'work-style', 3),

('Which subject or activity did you enjoy most in school/college?',
 '[
   {"text": "Mathematics, logic, or programming", "tags": ["tech","math","coding","data","problem-solving"]},
   {"text": "Arts, design, or creative subjects", "tags": ["design","creativity","visual","art","media"]},
   {"text": "Science, biology, health, or nature", "tags": ["healthcare","science","research","environment","agriculture"]},
   {"text": "People, law, society, or business", "tags": ["writing","communication","empathy","storytelling","law","business","social","education"]}
 ]'::jsonb, 'academic', 4),

('What does success look like to you in 5 years?',
 '[
   {"text": "Building or creating something meaningful that helps people", "tags": ["tech","coding","product","building","healthcare","helping"]},
   {"text": "Running my own business or creative venture", "tags": ["design","media","creativity","storytelling","art","entrepreneurship","business"]},
   {"text": "Leading a team and shaping strategy at a respected organization", "tags": ["leadership","business","strategy","planning","product","management"]},
   {"text": "Using expertise to protect, defend, understand, or improve the world", "tags": ["law","justice","security","science","research","environment","social"]}
 ]'::jsonb, 'goals', 5),

('How do you prefer to communicate your ideas?',
 '[
   {"text": "Through code, data, systems, or technical demonstrations", "tags": ["tech","data","problem-solving","infrastructure","trades"]},
   {"text": "Through visuals, mockups, designs, or creative presentations", "tags": ["design","visual","creativity","media"]},
   {"text": "Through writing, reports, plans, or thoughtful analysis", "tags": ["business","writing","analysis","finance","law","research"]},
   {"text": "Through conversations, presentations, or direct human connection", "tags": ["media","communication","storytelling","marketing","healthcare","education","social"]}
 ]'::jsonb, 'communication', 6);

-- ─────────────────────────────────────────
-- BADGES
-- ─────────────────────────────────────────
INSERT INTO badges (slug, name, description, icon_emoji, xp_reward) VALUES
('first_goal',       'Goal Setter',        'Created your first goal',                     '🎯', 50),
('first_focus',      'Focus Starter',      'Completed your first Pomodoro session',       '⏱️', 50),
('week_streak_7',    '7-Day Streak',       'Studied for 7 days in a row',                 '🔥', 200),
('week_streak_30',   '30-Day Warrior',     'Studied for 30 days straight',                '⚡', 1000),
('goal_crusher_5',   'Goal Crusher',       'Completed 5 goals',                           '💪', 300),
('career_explorer',  'Career Explorer',    'Saved 3 or more career paths',                '🧭', 100),
('quiz_taker',       'Path Finder',        'Completed the career quiz',                   '🔮', 100),
('mood_tracker_7',   'Self-Aware',         'Tracked your mood for 7 days',                '🧘', 150),
('study_100h',       'Century Club',       'Logged 100 hours of study time',              '💯', 500),
('roadmap_builder',  'Road Warrior',       'Created your first learning roadmap',         '🗺️', 100);
